version: '3'
services:
    php-fpm:
        container_name: ${CONTAINER_NAME}_php-fpm
        build:
            context: .
            dockerfile: PHP.Dockerfile
        #environment:
        #    APP_ENV: 'my env perso variable 2'
        volumes:
            - .:/app
        restart: always
    web:
        container_name: ${CONTAINER_NAME}_nginx
        image: nginx:latest
        ports:
            - "8888:80"
        links:
            - php-fpm
        volumes:
            - './:${WORKFOLDER}:rw'
            - './docker/nginx/conf/core/nginx.conf:/etc/nginx/nginx.conf'
            - './docker/nginx/conf/development/sfp.conf:/etc/nginx/conf.d/default.conf'
        restart: always
    mysql:
        container_name: ${CONTAINER_NAME}_mysql
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'secret'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'coucou'
            MYSQL_DATABASE: 'db123'
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 3306:3306
        restart: always
volumes:
    mysqldata: {}