version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "8888:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - .:/app
    php:
        image: php:fpm
        volumes:
            - .:/app